import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 10,
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 5,
  },
  bio: {
    fontSize: 12,
    color: '#64748b',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#334155',
    marginTop: 15,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    paddingBottom: 5,
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  skillBadge: {
    backgroundColor: '#eff6ff',
    color: '#3b82f6',
    padding: '4px 8px',
    borderRadius: 4,
    fontSize: 10,
    marginRight: 5,
    marginBottom: 5,
  },
  achievementItem: {
    marginBottom: 10,
  },
  achievementTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0f172a',
  },
  achievementMeta: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 2,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 10,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
  }
});

interface PortfolioPDFProps {
  profile: any;
  achievements: any[];
}

export const PortfolioPDF = ({ profile, achievements }: PortfolioPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.name}>{profile?.firstName} {profile?.lastName}</Text>
        {profile?.bio && <Text style={styles.bio}>{profile.bio}</Text>}
        {profile?.linkedinUrl && <Text style={styles.bio}>LinkedIn: {profile.linkedinUrl}</Text>}
      </View>

      {profile?.skills && profile.skills.length > 0 && (
        <View>
          <Text style={styles.sectionTitle}>Skills</Text>
          <View style={styles.skillsContainer}>
            {profile.skills.map((skill: string, idx: number) => (
              <Text key={idx} style={styles.skillBadge}>{skill}</Text>
            ))}
          </View>
        </View>
      )}

      <View>
        <Text style={styles.sectionTitle}>Verified Achievements</Text>
        {achievements && achievements.length > 0 ? (
          achievements.map((achievement, idx) => (
            <View key={idx} style={styles.achievementItem}>
              <Text style={styles.achievementTitle}>{achievement.title}</Text>
              <Text style={styles.achievementMeta}>
                {achievement.category} | Verified on {new Date(achievement.updatedAt).toLocaleDateString()}
              </Text>
              {achievement.description && (
                <Text style={{ fontSize: 11, color: '#475569', marginTop: 4 }}>
                  {achievement.description}
                </Text>
              )}
            </View>
          ))
        ) : (
          <Text style={styles.bio}>No verified achievements yet.</Text>
        )}
      </View>

      <View style={styles.footer}>
        <Text>Generated by Uni-Connect | The Smart Student Hub</Text>
      </View>
    </Page>
  </Document>
);

export default PortfolioPDF;
